name: CI-Back

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.SUBMODULE_TOKEN }}

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8

      - name: Grant execute permission for gradlew
        working-directory: ./back
        run: chmod +x gradlew

      - name: Build with Gradle (prod profile)
        working-directory: ./back
        run: ./gradlew clean build -Pprofile=prod

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_BACK_USERNAME }}
          password: ${{ secrets.DOCKERHUB_BACK_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./back
          file: ./back/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_BACK_USERNAME }}/back:latest
          build-args: |
            GOOGLE_ID=${{ secrets.GOOGLE_ID }}
            GOOGLE_SECRET=${{ secrets.GOOGLE_SECRET }}