# This is a basic workflow to help you get started with Actions

name: CI-Front

# Controls when the action will run.
on:
  workflow_run:
    workflows: [ "CI-Back" ]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Dependencies
        working-directory: ./front
        run: npm install

      - name: Build ReactJS
        env:
          CI: false
          REACT_APP_KAKAO_KEY: ${{ secrets.REACT_APP_KAKAO_KEY }}
        working-directory: ./front
        run: npm run build:prod

      - name: Login to DockerHub
        uses: docker/login-action@v1.8.0
        with:
          username: ${{ secrets.DOCKERHUB_FRONT_USERNAME }}
          password: ${{ secrets.DOCKERHUB_FRONT_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          file: front/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_FRONT_USERNAME}}/front:latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_IAM_MANAGER_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_IAM_MANAGER_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: run code deploy
        run: >
          aws deploy create-deployment 
          --application-name cocktailpick-prod 
          --deployment-config-name CodeDeployDefault.OneAtATime 
          --deployment-group-name cocktailpick-deploy-group
          --file-exists-behavior OVERWRITE
          --github-location repository=woowacourse-teams/2020-6rinkers,commitId=${{ GITHUB.SHA }}
